let shopItemsData = [
    {
      id: "0",
      name: "Quilted Shoulder Bag",
      price: 1395,
      desc: "Elevate your outfit with this elegant quilted shoulder bag.",
      img: "images/img1.jpg",
    },
    {
      id: "1",
      name: "Crossbody Bag",
      price: 160,
      desc: "A versatile crossbody bag that's both chic and practical.",
      img: "images/img2.jpg",
    },
    {
      id: "2",
      name: "Ergonomic Backpack",
      price: 895,
      desc: "Prioritize comfort and functionality with this ergonomic backpack.",
      img: "images/img3.jpg",
    },
    {
      id: "3",
      name: "Chic Tassel Tote",
      price: 1899,
      desc: "A fashion statement. This trendy tassel tote bag is ideal for both work and play.",
      img: "images/img4.jpg",
    },
    {
      id: "4",
      name: "Weekend Duffel Bag",
      price: 1000,
      desc: "Pack for your weekend getaway with ease using this spacious duffel bag.",
      img: "images/img5.jpg",
    },
    {
      id: "5",
      name: "Kids' Backpack",
      price: 750,
      desc: "Make going to school exciting for your little ones with this backpack.",
      img: "images/img6.jpg",
    },
    {
      id: "6",
      name: "Canvas Backpack",
      price: 800,
      desc: "This versatile cotton canvas backpack is both stylish and functional.",
      img: "images/img7.jpg",
    },
    {
      id: "7",
      name: "Classic Tote Bag",
      price: 90,
      desc: "This timeless tote bag features a spacious interior and sturdy handles",
      img: "images/img8.jpg",
    },
    {
      id: "8",
      name: "Satchel Handbag",
      price: 900,
      desc: "This handbag is perfect for adding a touch of class to any outfit.",
      img: "images/img9.jpg",
    },
    {
      id: "9",
      name: "Travel Suitcase",
      price: 1600,
      desc: "Designed to make your journeys hassle-free and convenient.",
      img: "images/img10.jpg",
    },
    {
      id: "10",
      name: "Black Tote Bag",
      price: 60,
      desc: "Perfect for carrying your everyday essentials in style",
      img: "images/img11.jpg",
    },
    {
      id: "11",
      name: "Sleek Laptop Bag",
      price: 600,
      desc: "Keep your laptop safe and secure with this sleek and professional laptop bag.",
      img: "images/img12.jpg",
    },
    {
      id: "12",
      name: "Sporty Gym Bag",
      price: 400,
      desc: "Sporty Gym Bag: Hit the gym in style with this sporty gym bag.",
      img: "images/img13.jpg",
    },
    {
      id: "13",
      name: "Trendy Fanny Pack",
      price: 75,
      desc: "Trendy Fanny Pack: Embrace the '90s revival with this trendy fanny pack.",
      img: "images/img14.jpg",
    }
  ];